/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.6 at Fri Apr 17 21:05:27 2015. */

#ifndef _PB_MESSAGE_PB_H_
#define _PB_MESSAGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _com_example_glowybits_rcp_ChangeSettings_Mode {
    com_example_glowybits_rcp_ChangeSettings_Mode_CHASE = 0,
    com_example_glowybits_rcp_ChangeSettings_Mode_STARS = 1,
    com_example_glowybits_rcp_ChangeSettings_Mode_SPIRAL = 2,
    com_example_glowybits_rcp_ChangeSettings_Mode_JOINT = 3
} com_example_glowybits_rcp_ChangeSettings_Mode;

/* Struct definitions */
typedef struct _com_example_glowybits_rcp_ChangeSettings {
    com_example_glowybits_rcp_ChangeSettings_Mode mode;
    int32_t brightness;
    float speed;
    float rainbow_speed;
    float width;
    uint32_t color1;
    uint32_t color2;
    uint32_t color3;
} com_example_glowybits_rcp_ChangeSettings;

typedef struct _com_example_glowybits_rcp_PingTest {
    uint32_t time_sent;
    pb_callback_t message;
} com_example_glowybits_rcp_PingTest;

typedef struct _com_example_glowybits_rcp_Status {
    uint32_t fps;
} com_example_glowybits_rcp_Status;

typedef struct _com_example_glowybits_rcp_RpcMessage {
    bool has_settings;
    com_example_glowybits_rcp_ChangeSettings settings;
    bool has_status;
    com_example_glowybits_rcp_Status status;
} com_example_glowybits_rcp_RpcMessage;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define com_example_glowybits_rcp_ChangeSettings_mode_tag 1
#define com_example_glowybits_rcp_ChangeSettings_brightness_tag 2
#define com_example_glowybits_rcp_ChangeSettings_speed_tag 3
#define com_example_glowybits_rcp_ChangeSettings_rainbow_speed_tag 4
#define com_example_glowybits_rcp_ChangeSettings_width_tag 5
#define com_example_glowybits_rcp_ChangeSettings_color1_tag 6
#define com_example_glowybits_rcp_ChangeSettings_color2_tag 7
#define com_example_glowybits_rcp_ChangeSettings_color3_tag 8
#define com_example_glowybits_rcp_PingTest_time_sent_tag 1
#define com_example_glowybits_rcp_PingTest_message_tag 2
#define com_example_glowybits_rcp_Status_fps_tag 1
#define com_example_glowybits_rcp_RpcMessage_settings_tag 1
#define com_example_glowybits_rcp_RpcMessage_status_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t com_example_glowybits_rcp_ChangeSettings_fields[9];
extern const pb_field_t com_example_glowybits_rcp_Status_fields[2];
extern const pb_field_t com_example_glowybits_rcp_PingTest_fields[3];
extern const pb_field_t com_example_glowybits_rcp_RpcMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define com_example_glowybits_rcp_ChangeSettings_size 50
#define com_example_glowybits_rcp_Status_size    6
#define com_example_glowybits_rcp_RpcMessage_size 60

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
