/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.6 at Thu Feb 20 23:09:26 2014. */

#ifndef _PB_MESSAGE_PB_H_
#define _PB_MESSAGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _com_example_glowybits_rcp_RpcMessage_Action {
    com_example_glowybits_rcp_RpcMessage_Action_FRAMES_PER_SECOND = 0,
    com_example_glowybits_rcp_RpcMessage_Action_CHANGE_MODE = 1,
    com_example_glowybits_rcp_RpcMessage_Action_CHANGE_BRIGHTNESS = 2,
    com_example_glowybits_rcp_RpcMessage_Action_DEBUG = 10
} com_example_glowybits_rcp_RpcMessage_Action;

/* Struct definitions */
typedef struct _com_example_glowybits_rcp_RpcMessage {
    com_example_glowybits_rcp_RpcMessage_Action action;
    bool has_arg1;
    int32_t arg1;
    bool has_description;
    char description[80];
} com_example_glowybits_rcp_RpcMessage;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define com_example_glowybits_rcp_RpcMessage_action_tag 1
#define com_example_glowybits_rcp_RpcMessage_arg1_tag 2
#define com_example_glowybits_rcp_RpcMessage_description_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t com_example_glowybits_rcp_RpcMessage_fields[4];

/* Maximum encoded size of messages (where known) */
#define com_example_glowybits_rcp_RpcMessage_size 99

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
