/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Wed Feb 26 20:16:35 2014. */

#include "message.pb.h"



const pb_field_t com_example_glowybits_rcp_RpcMessage_fields[6] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, com_example_glowybits_rcp_RpcMessage, rid, rid, 0),
    PB_FIELD2(  2, ENUM    , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, action, rid, 0),
    PB_FIELD2(  3, INT32   , OPTIONAL, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, arg1, action, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, description, arg1, 0),
    PB_FIELD2(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, arg2, description, 0),
    PB_LAST_FIELD
};


