/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.6 at Wed Oct  8 21:26:55 2014. */

#ifndef _PB_MESSAGE_PB_H_
#define _PB_MESSAGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _com_example_glowybits_rcp_ChangeSettings_Mode {
    com_example_glowybits_rcp_ChangeSettings_Mode_CHASE = 0,
    com_example_glowybits_rcp_ChangeSettings_Mode_STARS = 1,
    com_example_glowybits_rcp_ChangeSettings_Mode_LINES = 2,
    com_example_glowybits_rcp_ChangeSettings_Mode_SPIRAL = 3
} com_example_glowybits_rcp_ChangeSettings_Mode;

/* Struct definitions */
typedef struct _com_example_glowybits_rcp_ChangeSettings {
    com_example_glowybits_rcp_ChangeSettings_Mode mode;
    int32_t brightness;
    float speed;
    float rainbow_speed;
    float width;
} com_example_glowybits_rcp_ChangeSettings;

typedef struct _com_example_glowybits_rcp_Status {
    uint32_t fps;
} com_example_glowybits_rcp_Status;

typedef struct _com_example_glowybits_rcp_RpcMessage {
    bool has_settings;
    com_example_glowybits_rcp_ChangeSettings settings;
    bool has_status;
    com_example_glowybits_rcp_Status status;
} com_example_glowybits_rcp_RpcMessage;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define com_example_glowybits_rcp_ChangeSettings_mode_tag 1
#define com_example_glowybits_rcp_ChangeSettings_brightness_tag 2
#define com_example_glowybits_rcp_ChangeSettings_speed_tag 3
#define com_example_glowybits_rcp_ChangeSettings_rainbow_speed_tag 4
#define com_example_glowybits_rcp_ChangeSettings_width_tag 5
#define com_example_glowybits_rcp_Status_fps_tag 1
#define com_example_glowybits_rcp_RpcMessage_settings_tag 1
#define com_example_glowybits_rcp_RpcMessage_status_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t com_example_glowybits_rcp_ChangeSettings_fields[6];
extern const pb_field_t com_example_glowybits_rcp_Status_fields[2];
extern const pb_field_t com_example_glowybits_rcp_RpcMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define com_example_glowybits_rcp_ChangeSettings_size 32
#define com_example_glowybits_rcp_Status_size    6
#define com_example_glowybits_rcp_RpcMessage_size 42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
