/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Wed Feb 19 22:22:00 2014. */

#include "message.pb.h"



const pb_field_t com_example_glowybits_rcp_RpcMessage_fields[4] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, com_example_glowybits_rcp_RpcMessage, action, action, 0),
    PB_FIELD2(  2, INT32   , OPTIONAL, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, arg1, action, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, description, arg1, 0),
    PB_LAST_FIELD
};


