/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Fri Apr 17 21:05:27 2015. */

#include "message.pb.h"



const pb_field_t com_example_glowybits_rcp_ChangeSettings_fields[9] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, com_example_glowybits_rcp_ChangeSettings, mode, mode, 0),
    PB_FIELD2(  2, INT32   , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, brightness, mode, 0),
    PB_FIELD2(  3, FLOAT   , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, speed, brightness, 0),
    PB_FIELD2(  4, FLOAT   , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, rainbow_speed, speed, 0),
    PB_FIELD2(  5, FLOAT   , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, width, rainbow_speed, 0),
    PB_FIELD2(  6, UINT32  , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, color1, width, 0),
    PB_FIELD2(  7, UINT32  , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, color2, color1, 0),
    PB_FIELD2(  8, UINT32  , REQUIRED, STATIC  , OTHER, com_example_glowybits_rcp_ChangeSettings, color3, color2, 0),
    PB_LAST_FIELD
};

const pb_field_t com_example_glowybits_rcp_Status_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, com_example_glowybits_rcp_Status, fps, fps, 0),
    PB_LAST_FIELD
};

const pb_field_t com_example_glowybits_rcp_PingTest_fields[3] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, com_example_glowybits_rcp_PingTest, time_sent, time_sent, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, com_example_glowybits_rcp_PingTest, message, time_sent, 0),
    PB_LAST_FIELD
};

const pb_field_t com_example_glowybits_rcp_RpcMessage_fields[3] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, com_example_glowybits_rcp_RpcMessage, settings, settings, &com_example_glowybits_rcp_ChangeSettings_fields),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, com_example_glowybits_rcp_RpcMessage, status, settings, &com_example_glowybits_rcp_Status_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(com_example_glowybits_rcp_RpcMessage, settings) < 65536 && pb_membersize(com_example_glowybits_rcp_RpcMessage, status) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_com_example_glowybits_rcp_ChangeSettings_com_example_glowybits_rcp_Status_com_example_glowybits_rcp_PingTest_com_example_glowybits_rcp_RpcMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(com_example_glowybits_rcp_RpcMessage, settings) < 256 && pb_membersize(com_example_glowybits_rcp_RpcMessage, status) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_com_example_glowybits_rcp_ChangeSettings_com_example_glowybits_rcp_Status_com_example_glowybits_rcp_PingTest_com_example_glowybits_rcp_RpcMessage)
#endif


